version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome63
      environment:
        ## this enables colors + fixes failing unit tests
        TERM: xterm
        # avoid million NPM install messages
        npm_config_loglevel: warn
        # allow installing when the main user is root
        npm_config_unsafe_perm: true
  steps:
    - checkout
    - restore_cache:
        key: root-deps
    - run: npm install
    - run: npm prune
    - save_cache:
        key: root-deps-{{ checksum "package.json" }}
        paths:
          - node_modules
    - run:
        command: npm run server
        name: start the server
        background: true
    - run:
        command: npm run cy:run -- --record --env framework=$CIRCLE_JOB
        name: Test framework

jobs:
  backbone:
    <<: *defaults
  dojo:
    <<: *defaults
  react:
    <<: *defaults
  vue:
    <<: *defaults
  spine:
    <<: *defaults
  typescript-react:
    <<: *defaults
  binding-scala:
    <<: *defaults

workflows:
  version: 2
  # main JavaScript frameworks from the first tab
  main-frameworks:
    jobs:
      - backbone
      - dojo
      - react
      - vue
  # second tab - compiled-to-js frameworks
  compiled-to-js:
    jobs:
      - spine
      # elm is not working very well
      - typescript-react
      - binding-scala
