version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome63
      environment:
        ## this enables colors + fixes failing unit tests
        TERM: xterm
        # avoid million NPM install messages
        npm_config_loglevel: warn
        # allow installing when the main user is root
        npm_config_unsafe_perm: true
  steps:
    - checkout
    - restore_cache:
        key: root-deps
    - run: npm install
    - run: npm prune
    - save_cache:
        key: root-deps-{{ checksum "package.json" }}
        paths:
          - node_modules
    - run:
        command: npm run server
        name: start the server
        background: true
    - run:
        command: npm run cy:run -- --record --env framework=$CIRCLE_JOB
        name: Test framework

jobs:
  # main JS frameworks
  backbone:
    <<: *defaults
  dojo:
    <<: *defaults
  react:
    <<: *defaults
  vue:
    <<: *defaults
  angularjs:
    <<: *defaults
  knockback:
    <<: *defaults
  mithril:
    <<: *defaults
  backbone_marionette:
    <<: *defaults
  emberjs:
    <<: *defaults
  canjs:
    <<: *defaults
  ampersand:
    <<: *defaults
  troopjs_require:
    <<: *defaults
  knockoutjs:
    <<: *defaults
  polymer:
    <<: *defaults
  flight:
    <<: *defaults
  # compiled-to-js frameworks
  spine:
    <<: *defaults
  typescript-react:
    <<: *defaults
  binding-scala:
    <<: *defaults
  vanilladart:
    <<: *defaults
  angular-dart:
    <<: *defaults
  serenadejs:
    <<: *defaults
  js_of_ocaml:
    <<: *defaults
  reagent:
    <<: *defaults
  humble:
    <<: *defaults
  closure:
    <<: *defaults
  typescript-angular:
    <<: *defaults
  scalajs-react:
    <<: *defaults

workflows:
  version: 2
  # main JavaScript frameworks from the first tab
  main-frameworks:
    jobs:
      - backbone
      - dojo
      - react
      - vue
      - angularjs
      - knockback
      - mithril
      - backbone_marionette
      - emberjs
      - canjs
      - ampersand
      - troopjs_require
      - knockoutjs
      - polymer
      - flight
  # second tab - compiled-to-js frameworks
  compiled-to-js:
    jobs:
      - spine
      # elm is not working very well
      - typescript-react
      - binding-scala
      - vanilladart
      - angular-dart
      - serenadejs
      - js_of_ocaml
      - typescript-backbone
      - reagent
      - humble
      - closure
      - typescript-angular
      - scalajs-react
